# Generated by Django 5.0.6 on 2024-06-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='user_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mob_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
