# Generated by Django 5.0.6 on 2024-06-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_authorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_value', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='profile_images',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='user_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_title', models.CharField(max_length=400)),
                ('degree', models.CharField(max_length=400)),
                ('field_of_study', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(max_length=100)),
                ('activities_and_societies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='myapp.authorprofile')),
                ('skills', models.ManyToManyField(related_name='educations', to='myapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=400)),
                ('company_name', models.CharField(max_length=250)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo_image/')),
                ('company_portfolio_link', models.URLField(blank=True, null=True)),
                ('working_time', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelance', 'Freelance')], max_length=10)),
                ('working_type', models.CharField(choices=[('Remote', 'Remote'), ('On-Site', 'On-Site'), ('Hybrid', 'Hybrid')], max_length=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('activities_responsibilities', models.TextField(blank=True, null=True)),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='myapp.authorprofile')),
                ('skills', models.ManyToManyField(related_name='work_experiences', to='myapp.skill')),
            ],
        ),
    ]
